services:

  # DATABASE SERVICE
  postgres:
    image: postgres:15
    container_name: database_container
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: quote_vault_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # SERVER SERVICE
  server:
    container_name: nest_server
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - ./server:/app
      # Mount PNPM store to preserve dependencies
      - /root/.pnpm-store
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USER: admin
      DATABASE_PASSWORD: password123
      DATABASE_NAME: quote_vault_db
    command: pnpm start:dev

  # CLIENT SERVICE
  client:
    container_name: vue_client
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - ./client:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    command: pnpm dev
    depends_on:
      - postgres

volumes:
  postgres_data:
